<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Madhukar" failures="1" tests="5" name="testRunner.TestRun" time="89.633" errors="0" timestamp="2025-06-19T04:57:33 IST" skipped="0">
  <testcase classname="testRunner.TestRun" name="runScenario" time="14.440"/>
  <testcase classname="testRunner.TestRun" name="runScenario" time="22.122">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at stepDefinations.StepsDefi.user_can_view_confirmation_message(StepsDefi.java:295)
at âœ½.User can view confirmation message "Warning: You do not have permission to modify customers!!"(file:///D:/Automation/myworkspace/repository4/OpenCart_Administation_V1.0/./Features/Customers.feature:18)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.TestRun" name="runScenario" time="17.681"/>
  <testcase classname="testRunner.TestRun" name="runScenario" time="16.593"/>
  <testcase classname="testRunner.TestRun" name="runScenario" time="18.797"/>
</testsuite> <!-- testRunner.TestRun -->
